config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  authenticate :user do
    namespace :admin do
      # resources :schedules
      # resources :reservations
      # resources :payments
      # resources :courts
      # resources :comunas
      resources :clubs
      # resources :availabilities
      resources :users

      root to: "clubs#index"
    end
  end

  resources :clubs, only: %i[show index]
  resources :subscriptions, only: %i[new create]

  devise_for :users,
             controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               sessions: "users/sessions",
               registrations: "users/registrations"
             }

  resources :reservations do
    collection { get "availability" }
  end

  root "pages#home"
  get "debug" => "pages#debug"
  get "availability" => "availability#index"

  get "mp_payment_success" => "payments#mp_payment_success"
  get "mp_payment_failiure" => "payments#mp_payment_failiure"
  get "privacidad" => "pages#privacidad"

  get "privio" => "pages#privio"
end

app/models/reservation.rb
# == Schema Information
#
# Table name: reservations
#
#  id         :bigint           not null, primary key
#  ends_at    :datetime
#  starts_at  :datetime
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  court_id   :integer
#  user_id    :integer
#
class Reservation < ApplicationRecord
  require "date_time_extensions.rb"

  belongs_to :user
  validates :user, presence: true

  belongs_to :court
  validates :court, presence: true

  has_many :payments, as: :payable
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  validates :ends_at, comparison: { greater_than: :starts_at }

  validates :court_id,
            uniqueness: {
              scope: :starts_at,
              message:
                "Disculpa pero este horario parece ya no estar disponible."
            }
  validates :court_id,
            uniqueness: {
              scope: :ends_at,
              message:
                "Disculpa pero este horario parece ya no estar disponible."
            }

  def club
    court.club
  end

  def duration
    ((ends_at - starts_at) / 60).to_i
  end

  def paid?
    self.payments.where(status: :approved).any?
  end

  def price
    price_for_30_min = {
      (0.0..8.5) => 4000,
      (8.0..17.0) => 3000,
      (17...24) => 5000
    }
    price = 0
    starts_at
      .decimal_hour
      .step(by: 0.5, to: ends_at.decimal_hour - 0.5) do |st|
        price += price_for_30_min.select { |h| h === st / 1.0 }.values.first
      end
    return price
  end
end

app/controllers/admin/reservations_controller.rb
module Admin
  class ReservationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: %i[show edit update destroy]

  def availability
    @club = Club.find(params[:club])
    @from_date =
      params[:from_date].blank? ? Date.today : Date.parse(params[:from_date])
    @selected_date =
      params[:from_date].blank? ? @from_date : Date.parse(params[:date])
  end

  # GET /reservations or /reservations.json
  def index
    @reservations = current_user.reservations.all.order(:starts_at)
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation =
      Reservation.new(
        starts_at: params[:starts_at],
        ends_at: params[:ends_at],
        court_id: params[:court_id]
      )
  end

  def pay
  end

  # GET /reservations/1/edit
  def edit
    @preference_data = {
      back_urls: {
        success: "#{request.host_with_port}/mp_payment_success",
        failure: "#{request.host_with_port}/mp_payment_failiure",
        pending: "http://localhost:3000/"
      },
      items: [
        {
          id: "#{@reservation.id}",
          category_id: "reservation",
          title:
            "Reserva Padel #{l(@reservation.starts_at, format: "%A %e %b %k:%M")}.",
          unit_price: @reservation.price,
          quantity: 1
        }
      ],
      payer: {
        email: "#{@reservation.user.email}"
      },
      binary_mode: true,
      external_reference: "Reservation/#{@reservation.id}"
    }
    sdk = Mercadopago::SDK.new(ENV["MERCADOPAGO_TEST_ACCESS_TOKEN"])
    preference_response = sdk.preference.create(@preference_data)
    @preference = preference_response[:response]
    # Este valor reemplazará el string "<%= @preference_id %>" en tu HTML
    @preference_id = @preference["id"]
    # @reservation.payments.create(preference_id: @preference_id, status: "pending")
  end

  # POST /reservations or /reservations.json
  def create
    if current_user
      user = current_user
    elsif User.find_by(email: params[:user][:email])
      user = User.find_by(email: params[:user][:email])
    else
      user =
        User.new(email: params[:user][:email], phone: params[:user][:phone])
      user.password = "1234"
      user.save(validate: false)
    end
    sign_in user
    @reservation = Reservation.new(reservation_params)
    @reservation.user = user

    respond_to do |format|
      if @reservation.save
        flash[:notice] = "Reserva creada pendiente de pago ;)"
        format.html { redirect_to edit_reservation_path @reservation }
        format.json { render :show, status: :created, location: @reservation }
      else
        flash[:alert] = @reservation.errors.full_messages.first
        format.html { redirect_to root_path }
        format.json do
          render json: @reservation.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html do
          redirect_to reservation_url(@reservation),
                      notice: "Reservation was successfully updated."
        end
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @reservation.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html do
        redirect_to reservations_path, notice: "Cancelamos tu reserva. "
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reservation_params
    params.require(:reservation).permit(
      :user_id,
      :court_id,
      :starts_at,
      :ends_at,
      :court_number
    )
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def wa_invitation_text reservation
    base_url = "https://wa.me/?text="
    message = ""
    message += "Cancha Reservada! %0A%0A"
    message += "#{l(reservation.starts_at, format: "%A %e %b %k:%M").capitalize}"
    message += " (#{reservation.duration} min)%0A"
    message += "#{reservation.club.name} (Cancha %23#{reservation.court.number})%0A"

    "#{base_url}#{message}"
  end
end

app/views/reservations/_availability.html.haml
%div{"data-controller" => "spinner"}
  .mt-3
    = render partial: "shared/date_selector", locals: {path: club_path(@club)}
    = render "layouts/spinner"
    #contentDiv{"data-spinner-target"=> "contentDiv"}
      .text-dark.py-3.fs-6
        #{@duration} Minutos
      - unless availability.blank?
        - availability.slots.values.in_groups_of(4, nil) do |slots|
          .row.pb-2
            - slots.each do |slot|
              .col-3
                - if slot
                  - if current_user
                    .d-grid.gap-2
                      - reservation = Reservation.new(starts_at: slot["starts_at"], ends_at: slot["ends_at"], court_id: slot["courts"].first["court_id"])
                      - reservation.user = current_user
                      = form_with model: reservation, html: {data: {turbo: false}} do |form|
                        = form.hidden_field "user_id"
                        = form.hidden_field "court_id"
                        = form.hidden_field "starts_at"
                        = form.hidden_field "ends_at"
                        = form.submit "#{slot["starts_at"].in_time_zone.strftime("%H:%M")}", class: "btn btn-outline-secondary btn-block"
                  - else
                    .d-grid.gap-2
                      = link_to new_reservation_path(starts_at: "#{slot["starts_at"]}", ends_at: "#{slot["ends_at"]}", court_id: "#{slot["courts"].first["court_id"]}"), |
                                  data: { turbo: false }, type: :button, class: "btn btn-outline-secondary btn-block" do
                        =slot["starts_at"].in_time_zone.strftime("%H:%M")

app/views/reservations/_card.html.haml
- style = reservation.paid? ? 'success' : 'dark'
.div{style: "padding: 0 0 12px 0;"}
  .row
    .col-12
      .card{class: "border-#{style}"}
        .card-header.text-white{class: "text-bg-#{style}"}
          .row
            .col-6.text-start
              -if !reservation.persisted?
              - elsif reservation.paid?
                CONFIRMADA
              - else
                PAGO PENDIENTE
            .col-6.text-end.fw-bolder
              = number_to_currency reservation.price
        .card-body
          %h4.card-title
            #{l(reservation.starts_at, format: "%A %e %b %k:%M").capitalize} -
            #{reservation.ends_at.strftime(" %k:%M")}
            .small.fw-light
              #{reservation.duration} minutos
          %h5.card-subtitle
            = reservation.club.name
            %br
            %small.fw-light
              Cancha #{reservation.court.number}
          = link_to reservation.club.google_maps_link, target: :blank, class: "text-decoration-none link-secondary" do
            %span{class: "bi bi-geo-alt-fill"}
            = reservation.club.address
        .card-footer
          =render partial: 'card_footer', locals: {reservation: reservation}

app/views/reservations/_card_footer.html.haml
.row
  - if current_user
    - if reservation.paid?
      .col-12.text-end
        = link_to wa_invitation_text(reservation), class: "btn btn-success",  target: :blank do
          %i{class: "bi bi-whatsapp"}
          Invitar amigos
    - else
      .col-4.text-start
        = button_to 'Anular', reservation, method: :delete, type: :button, |
                  class: "btn btn-outline-secondary", |
                  form: { data: { "turbo_confirm": '¿Estás seguro de cancelar la reserva?' }}

      - if current_page?(reservations_path) and not(reservation.paid?)
        .col-8.text-end
          = button_to "Ir a Pagar", edit_reservation_path(reservation), type: :button, |
                      class: "btn btn-outline-secondary", method: :get, data: {turbo: false}
      - else
        .col-3.text-end
          = image_tag "mercado_pago.png", class: "mercado-pago-img float-start float-middle", style: "max-width: 90px;"
        .col-5.text-end
          .mp-cho-btn
  - else
    .row
      .col-12
        = form_with model: reservation do |form|
          = form.hidden_field :starts_at
          = form.hidden_field :ends_at
          = form.hidden_field :court_id
          = fields_for :user, reservation.user do |user_form|
            .mb-3
              = user_form.label :email, "✉️ Email"
              = user_form.email_field :email, required: true, class: "form-control"
            .mb-3
              = user_form.label :phone, "📞 Teléfono"
              = user_form.number_field :phone, required: true, class: "form-control"
          .d-
          = form.submit "Crear Reserva", class: "btn btn-warning"

app/views/reservations/_form.html.haml
-# - style = reservation.paid? ? 'success' : 'dark'
-# .div{style: "padding: 0 0 12px 0;"}
-#   .row
-#     .col-12
-#       .card{class: "border-#{style}"}
-#         .card-header.text-white{class: "text-bg-#{style}"}
-#             .col-6.text-start
-#           .row
-#               -if reservation.paid?
-#                 CONFIRMADA
-#               - else
-#                 PAGO PENDIENTE
-#             .col-6.text-end.fw-bolder
-#               = number_to_currency reservation.price
-#         .card-body
-#           %h4.card-title
-#             #{l(reservation.starts_at, format: "%A %e %b %k:%M").capitalize} -
-#             #{reservation.ends_at.strftime(" %k:%M")}
-#             .small.fw-light
-#               #{reservation.duration} minutos
-#           %h5.card-subtitle
-#             = reservation.club.name
-#             %br
-#             %small.fw-light
-#               Cancha #{reservation.court.number}
-#           = link_to reservation.club.google_maps_link, target: :blank, class: "text-decoration-none link-primary" do
-#             %span{class: "bi bi-geo-alt-fill"}
-#             = reservation.club.address
-#         .card-footer
-#           .row
-#             - if current_user
-#               - if reservation.paid?
-#                 .col-12.text-end
-#                   = link_to wa_invitation_text(reservation), class: "btn btn-success",  target: :blank do
-#                     %i{class: "bi bi-whatsapp"}
-#                     Invitar amigos
-#               - else
-#                 .col-4.text-start
-#                   = button_to 'Cancelar', reservation, method: :delete, type: :button, |
-#                             class: "btn btn-outline-secondary", data: { "turbo_confirm": '¿Estás seguro de cancelar la reserva?' }
-#
-#                 - if current_page?(reservations_path) and not(reservation.paid?)
-#                   .col-8.text-end
-#                     = link_to "Ir a Pagar", edit_reservation_path(reservation), type: :button, class: "btn btn-#{style}", data: {turbo: false}
-#                 - else
-#                   .col-3.text-end
-#                     = image_tag "mercado_pago.png", class: "mercado-pago-img float-start float-middle", style: "max-width: 90px;"
-#                   .col-5.text-end
-#                     .mp-cho-btn
-#             - else
-#               Ingresa estos datos v

app/views/reservations/availability.html.haml
.container
    =render partial: "availability", locals: {club: @club}

app/views/reservations/edit.html.haml
:javascript
  // "TEST-bf1bb044-2358-4212-9eb3-8a9bf7999e12"
  // "#{ENV['MERCADOPAGO_TEST_PUBLIC_KEY']}"
    const mp_co = new MercadoPago("#{ENV['MERCADOPAGO_TEST_PUBLIC_KEY']}", {
          locale: 'es-CL'
    });

    // Inicializa el checkout
    window.onload = setTimeout(load_mp_button, 800);

    function load_mp_button() {
      mp_co.checkout({
          preference: {
              id: "#{@preference_id}"
          },
          render: {
                container: '.mp-cho-btn', // Indica el nombre de la clase donde se mostrará el botón de pago
                label: 'PAGAR', // Cambia el texto del botón de pago (opcional)
          }
      });
    }

.div-text-center
  = render partial: 'card', |
           locals: {reservation: @reservation}

app/views/reservations/index.html.haml
.container
  .row{style: "padding: 12px 0 24px 0;"}
    .col-6.text-start
      .fs-4
        Mis Reservas
    .col-6.text-end
      %fs-4
        =link_to availability_path, type: :button, class: "btn btn-outline-dark btn-sm" do
          %i{class: "bi bi-plus"}
          Nueva Reserva

  .div-text-center
    - pending_payment = @reservations.select{|r| not r.paid?}
    - if pending_payment.any?
      - pending_payment.each do |reservation|
        =render partial: 'card', locals: {reservation: reservation}

    - paid = @reservations.select{|r| r.paid?}
    - if paid.any?
      - paid.each do |reservation|
        =render partial: 'card', locals: {reservation: reservation}

app/views/reservations/new.html.haml
= render partial: "card", locals: {reservation: @reservation}

app/views/reservations/show.html.haml
.container
  .row{style: "padding: 12px 0 24px 0;"}
    .col-6.text-start
      .fs-4
        Reserva ##{@reservation.id}
  .div-text-center
    = render partial: 'card', |
        locals: {reservation: @reservation}
  .row{style: "padding: 12px 0 24px 0;"}
    .col-6.text-start
      = button_to "Ver todas mis reservas", reservations_path, method: :get, class: "btn btn-link"
    .col-6.text-end
      =button_to root_path, method: :get, type: :button, class: "btn btn-outline-dark btn-sm" do
        %i{class: "bi bi-plus"}
        Nueva Reserva