config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  authenticate :user do
    namespace :admin do
      # resources :schedules
      # resources :reservations
      # resources :payments
      # resources :courts
      # resources :comunas
      resources :clubs
      # resources :availabilities
      resources :users

      root to: "clubs#index"
    end
  end

  resources :clubs, only: %i[show index]
  resources :subscriptions, only: %i[new create]

  devise_for :users,
             controllers: {
               omniauth_callbacks: "users/omniauth_callbacks",
               sessions: "users/sessions",
               registrations: "users/registrations"
             }

  resources :reservations do
    collection { get "availability" }
  end

  root "pages#home"
  get "debug" => "pages#debug"
  get "availability" => "availability#index"

  get "mp_payment_success" => "payments#mp_payment_success"
  get "mp_payment_failiure" => "payments#mp_payment_failiure"
  get "privacidad" => "pages#privacidad"

  get "privio" => "pages#privio"
end

app/views/layouts/_footer.html.haml
.div.mt-4{style: "background-color: #EBEBEB;"}
  .container.nav-container  
    %footer
      .row.row-cols-1.row-cols-sm-2.row-cols-md-5.py-3.mt-3
        .col.mb-3
          %h5 Encuentra
          %ul.nav.flex-column
            %li.nav-item.mb-2
              %a.nav-link.p-0.text-muted(href="#{clubs_path}")
                Clubes
            %li.nav-item.mb-2
              %a.nav-link.p-0.text-muted(href="#{availability_path}")
                Canchas
        .col.mb-3
          -# %h5 Tu Espacio
          -# %ul.nav.flex-column
          -#   %li.nav-item.mb-2
          -#     %a.nav-link.p-0.text-muted(href="#{reservations_path}")
          -#       Reservas
          -#   %li.nav-item.mb-2
          -#     %a.nav-link.p-0.text-muted(href="#")
          -#       Partidos

        .col.mb-3
          %h5 Sobre
          %ul.nav.flex-column
            %li.nav-item.mb-2
              %a.nav-link.p-0.text-muted(href="#{privacidad_path}")
                Privacidad

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-dark{style: "background-color: #EBEBEB;"}
  .container
    %a.navbar-brand.fw-bolder.text-dark{:href => root_path}
      -# = @club ? @club.name.gsub(" ", "_").camelize :   "TodoPadel"
      Padel64
    - if Rails.env.development?
      - if not(current_page? reservations_path) and current_user
        %a.nav-link{:href => reservations_path} Mis Reservas
    - if user_signed_in?
      %a.nav-link{:href => edit_user_registration_path}
        %i{class: "bi bi-person"}
    - else
      .div
      = link_to "Entrar", new_user_session_path, type: :button, class: "btn btn-link text-decoration-none"
      = link_to "Empezar", new_user_registration_path, type: :button, class: "btn btn-primary text-decoration-none"

app/views/layouts/_spinner.html.haml
.d-flex.justify-content-center
  .spinner-border.m-5#spinnerDiv{"data-spinner-target"=> "spinnerDiv"}

app/views/layouts/application.html.haml
=console if Rails.env.development?
!!!
%html
  %head
    %title Padel64.com
    %meta{name: "description", content: "Encuentra canchas y rivales para jugar más partidos, más peleados."}
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    %script{:src => "https://sdk.mercadopago.com/js/v2"}
  %body.d-flex.flex-column.min-vh-100
    = render "layouts/navbar"
    .root-container.container.pt-2
      .row
        - if alert
          .alert.alert-warning{:role => "alert"}
            = alert
        - if notice
          .alert.alert-primary{:role => "alert"}
            = notice
      = yield
    - #########
    - if Rails.env.development? and false
      .root-container.container.border-top.mt-4
        .row.mt-5
          %h5.text-center Development Zone
          %ul.mt-2
            %li.nav= link_to "Mis Reservas", reservations_path
          -# %li= link_to ""
    - ##########
    .mt-auto
    = render "layouts/footer"

app/views/layouts/bootstrap-mailer.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "x-apple-disable-message-reformatting"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "telephone=no, date=no, address=no, email=no", :name => "format-detection"}/
  %body
    = yield